import request from 'supertest';
import mongoose from 'mongoose';
import { MongoMemoryServer } from 'mongodb-memory-server';
import { connectDatabase, disconnectDatabase } from '../src/config/db.js';
import { createApp } from '../src/app.js';
import { attachRealtimeServer } from '../src/config/realtime.js';
import { OrganisationMember } from '../src/models/index.js';

let mongo, app, owner, member, organisationId, workspaceId, projectId, board, taskId;
const register = async (name,email,username) => (await request(app).post('/api/v1/auth/register').send({ fullName:name,email,username,password:'Testing@123' })).body.data;
const auth = (token,org=organisationId) => ({ Authorization:`Bearer ${token}`,'X-Organisation-Id':org });

beforeAll(async()=>{process.env.NODE_ENV='test';mongo=await MongoMemoryServer.create({instance:{args:['--nounixsocket']}});await connectDatabase(mongo.getUri());app=createApp();owner=await register('Owner User','owner@test.local','owner.user');member=await register('Member User','member@test.local','member.user');});
afterAll(async()=>{await disconnectDatabase();if(mongo)await mongo.stop();});

describe('authentication',()=>{
  test('registers, logs in and rotates the refresh token without exposing password data',async()=>{const response=await request(app).post('/api/v1/auth/login').send({email:'owner@test.local',password:'Testing@123'});expect(response.status).toBe(200);expect(response.body.data.accessToken).toBeTruthy();expect(response.body.data.user.passwordHash).toBeUndefined();expect(response.headers['set-cookie'][0]).toContain('HttpOnly');const refresh=await request(app).post('/api/v1/auth/refresh').set('Cookie',response.headers['set-cookie']);expect(refresh.status).toBe(200);expect(refresh.body.data.accessToken).toBeTruthy();expect(refresh.headers['set-cookie'][0]).toContain('HttpOnly');});
  test('handles simultaneous refresh attempts without an internal server error',async()=>{const login=await request(app).post('/api/v1/auth/login').send({email:'owner@test.local',password:'Testing@123'});const cookie=login.headers['set-cookie'];const responses=await Promise.all([request(app).post('/api/v1/auth/refresh').set('Cookie',cookie),request(app).post('/api/v1/auth/refresh').set('Cookie',cookie)]);expect(responses.some((response)=>response.status===200)).toBe(true);expect(responses.every((response)=>response.status!==500)).toBe(true);});
  test('rejects a protected route without a token',async()=>{const response=await request(app).get('/api/v1/organisations');expect(response.status).toBe(401);});
});
describe('realtime transport',()=>{
  test('serves the Socket.IO polling handshake through app.listen without Express returning 404',async()=>{const realtimeApp=createApp();const server=realtimeApp.listen(0);const io=attachRealtimeServer(realtimeApp,server);const response=await request(server).get('/socket.io/?EIO=4&transport=polling');expect(response.status).toBe(200);expect(response.text.startsWith('0')).toBe(true);await new Promise((resolve)=>io.close(resolve));});
});
describe('tenant resources and permissions',()=>{
  test('creates an organisation and default workspace',async()=>{const response=await request(app).post('/api/v1/organisations').set(auth(owner.accessToken,null)).send({name:'Test Organisation',description:'Integration suite'});expect(response.status).toBe(201);organisationId=response.body.data.organisation.id;workspaceId=response.body.data.workspace.id;expect(response.body.data.organisation.role).toBe('owner');});
  test('creates a project and its default board',async()=>{const response=await request(app).post('/api/v1/projects').set(auth(owner.accessToken)).send({workspaceId,name:'Launch Project',description:'Ship a release',color:'#FF745F'});expect(response.status).toBe(201);projectId=response.body.data.project.id;const boardResponse=await request(app).get(`/api/v1/boards/project/${projectId}`).set(auth(owner.accessToken));expect(boardResponse.status).toBe(200);expect(boardResponse.body.data.columns).toHaveLength(4);board=boardResponse.body.data;});
  test('invites a user by username and lets that user accept in the app',async()=>{const invite=await request(app).post(`/api/v1/organisations/${organisationId}/invitations`).set(auth(owner.accessToken)).send({username:member.user.username,role:'member'});expect(invite.status).toBe(201);expect(invite.body.data.invitation.invitedUser.username).toBe(member.user.username);const pending=await request(app).get('/api/v1/invitations').set('Authorization',`Bearer ${member.accessToken}`);expect(pending.status).toBe(200);expect(pending.body.data.invitations).toHaveLength(1);const response=await request(app).post('/api/v1/invitations/respond').set('Authorization',`Bearer ${member.accessToken}`).send({invitationId:pending.body.data.invitations[0].id,action:'accept'});expect(response.status).toBe(200);expect(response.body.data.invitation.status).toBe('accepted');expect(await OrganisationMember.exists({organisationId,userId:member.user.id,role:'member'})).toBeTruthy();});
  test('enforces role permissions',async()=>{const response=await request(app).post('/api/v1/projects').set(auth(member.accessToken)).send({workspaceId,name:'Forbidden Project'});expect(response.status).toBe(403);});
  test('prevents cross-organisation access',async()=>{const second=await request(app).post('/api/v1/organisations').set(auth(member.accessToken,null)).send({name:'Other Tenant'});const response=await request(app).get(`/api/v1/projects/${projectId}`).set(auth(member.accessToken,second.body.data.organisation.id));expect(response.status).toBe(404);});
  test('ignores an orphaned membership instead of failing the team endpoint',async()=>{const orphan=await OrganisationMember.create({organisationId,userId:new mongoose.Types.ObjectId(),role:'member'});const response=await request(app).get(`/api/v1/organisations/${organisationId}/members`).set(auth(owner.accessToken));expect(response.status).toBe(200);expect(response.body.data.members.every((row)=>row.userId)).toBe(true);await orphan.deleteOne();});
});
describe('task collaboration',()=>{
  test('creates and reads a task',async()=>{const response=await request(app).post('/api/v1/tasks').set(auth(owner.accessToken)).send({projectId,columnId:board.columns[0].id,title:'Integration task',priority:'high',assignees:[owner.user.id]});expect(response.status).toBe(201);taskId=response.body.data.task.id;const get=await request(app).get(`/api/v1/tasks/${taskId}`).set(auth(owner.accessToken));expect(get.status).toBe(200);expect(get.body.data.task.title).toBe('Integration task');});
  test('persists Kanban movement',async()=>{const response=await request(app).patch(`/api/v1/tasks/${taskId}/move`).set(auth(owner.accessToken)).send({columnId:board.columns[1].id,position:0});expect(response.status).toBe(200);expect(response.body.data.task.columnId.id).toBe(board.columns[1].id);});
  test('creates a comment',async()=>{const response=await request(app).post('/api/v1/comments').set(auth(owner.accessToken)).send({taskId,body:'Ready for review'});expect(response.status).toBe(201);expect(response.body.data.comment.body).toBe('Ready for review');});
  test('updates and deletes the task',async()=>{const update=await request(app).patch(`/api/v1/tasks/${taskId}`).set(auth(owner.accessToken)).send({priority:'urgent'});expect(update.status).toBe(200);expect(update.body.data.task.priority).toBe('urgent');const remove=await request(app).delete(`/api/v1/tasks/${taskId}`).set(auth(owner.accessToken));expect(remove.status).toBe(200);});
});
describe('direct chat',()=>{
  test('sends, saves and reads a message with a file attachment',async()=>{const sent=await request(app).post(`/api/v1/chat/${member.user.id}/messages`).set(auth(owner.accessToken)).field('body','Hello from TaskFlow 😀').attach('files',Buffer.from('chat attachment'),'notes.txt');expect(sent.status).toBe(201);expect(sent.body.data.message.body).toBe('Hello from TaskFlow 😀');expect(sent.body.data.message.attachments).toHaveLength(1);const attachment=sent.body.data.message.attachments[0];const download=await request(app).get(`/api/v1/chat/messages/${sent.body.data.message.id}/attachments/${attachment.id}/download`).set(auth(owner.accessToken));expect(download.status).toBe(200);expect(download.headers['content-disposition']).toContain('notes.txt');const memberList=await request(app).get('/api/v1/chat/members').set(auth(member.accessToken));expect(memberList.status).toBe(200);expect(memberList.body.data.members.find((item)=>item.id===owner.user.id).unread).toBe(1);const received=await request(app).get(`/api/v1/chat/${owner.user.id}/messages`).set(auth(member.accessToken));expect(received.status).toBe(200);expect(received.body.data.messages[0].attachments[0].name).toBe('notes.txt');const removed=await request(app).delete(`/api/v1/files/${attachment.fileId}`).set(auth(owner.accessToken));expect(removed.status).toBe(200);});
  test('supports delete for me and sender-only delete for everyone',async()=>{const sent=await request(app).post(`/api/v1/chat/${member.user.id}/messages`).set(auth(owner.accessToken)).field('body','Temporary message');const messageId=sent.body.data.message.id;const hidden=await request(app).delete(`/api/v1/chat/messages/${messageId}?scope=me`).set(auth(member.accessToken));expect(hidden.status).toBe(200);const memberView=await request(app).get(`/api/v1/chat/${owner.user.id}/messages`).set(auth(member.accessToken));expect(memberView.body.data.messages.some((item)=>item.id===messageId)).toBe(false);const ownerView=await request(app).get(`/api/v1/chat/${member.user.id}/messages`).set(auth(owner.accessToken));expect(ownerView.body.data.messages.some((item)=>item.id===messageId)).toBe(true);const forbidden=await request(app).delete(`/api/v1/chat/messages/${messageId}?scope=everyone`).set(auth(member.accessToken));expect(forbidden.status).toBe(403);const deleted=await request(app).delete(`/api/v1/chat/messages/${messageId}?scope=everyone`).set(auth(owner.accessToken));expect(deleted.status).toBe(200);const finalView=await request(app).get(`/api/v1/chat/${member.user.id}/messages`).set(auth(owner.accessToken));const tombstone=finalView.body.data.messages.find((item)=>item.id===messageId);expect(tombstone.body).toBe('');expect(tombstone.deletedForEveryoneAt).toBeTruthy();});
});
